name: Deploy

on:
  workflow_run:
    workflows: [ 'Tests' ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # Minimal permissions
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate Environment
      run: |
        echo "Deploying to Railway..."
        echo "Branch: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}"

    - uses: ./.github/actions/build
      # Add caching here if the build step installs dependencies
      # Example:
      # with:
      #   cache-key: ${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install Railway CLI
      run: pnpm add -g @railway/cli

    - name: Deploy to Railway
      run: railway up --service="emoji-gen"
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Notify on Failure (optional)
      if: failure()
      run: echo "Deployment failed! Check logs." # Replace with Slack/email/webhook
